apiVersion: v1
kind: ReplicationController
metadata:
  name: clair
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
      - name: clair
        image: quay.io/coreos/clair:v2.0.9
        args:
          - "-config"
          - "/config/config.yaml"
        ports:
        - containerPort: 6060
        - containerPort: 6061
        volumeMounts:
        - name: config
          mountPath: /config/config.yaml
          subPath: clair-config.yml
        - name: rootca
          mountPath: /usr/local/share/ca-certificates/operator.crt
          subPath: ca.crt
      volumes:
      - name: config
        configMap:
          name: clair-config
      - name: rootca
        secret:
          secretName: registry-ca