apiVersion: v1
kind: ReplicationController
metadata:
  name: clair
spec:
  template:
    spec:
      containers:
      - name: clair
        volumeMounts:
          - name: cert
            mountPath: /etc/ssl/certs/operator.crt
            subPath: ca.crt
      volumes:
      - name: cert
        secret:
          secretName: registry-ca