apiVersion: v1
kind: ReplicationController
metadata:
  name: arminc-clair
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: arminc-clair
    spec:
      containers:
      - name: clair
        image: arminc/clair-local-scan:latest
        args:
          - "-config"
          - "/config/config.yaml"
        ports:
        - containerPort: 6060
        - containerPort: 6061
        volumeMounts:
        - name: config
          mountPath: /config/config.yaml
          subPath: clair-config.yml
      volumes:
      - name: config
        configMap:
          name: clair-config
     