apiVersion: v1
kind: Service
metadata:
  name: clair
  labels:
    app: clair
spec:
  selector:
    app: clair
  ports:
  - name: api
    protocol: TCP
    port: 6060
  - name: health
    protocol: TCP
    port: 6061
  type: NodePort
  