apiVersion: v1
kind: ReplicationController
metadata:
  name: clair
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
      - name: clair
        image: clair
        args:
          - -conf
          - "/config/config.yaml"
          - mode
          - "combo"
        ports:
        - containerPort: 6060
        - containerPort: 6061
        volumeMounts:
        - name: config
          mountPath: /config/config.yaml
          subPath: clair-config.yml
      volumes:
      - name: config
        configMap:
          name: clair-config
