apiVersion: v1
kind: ReplicationController
metadata:
  name: clair-db
  labels:
    app: clair-db
spec:
  replicas: 1
  selector:
    app: clair-db
  template:
    metadata:
      labels:
        app: clair-db
    spec:
      containers:
      - name: clairdb
        image: clairdb
        env:
        - name: POSTGRES_USER
          value: tmax
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: clair
        ports:
        - name: postgres-port
          containerPort: 5432
